spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanagement
    username: root
    password: abc@3324
    driver-class-name: com.mysql.cj.jdbc.Driver

#JPA Settings
    jpa.hibernate.ddl-auto: create

